sudo: required
services:
- docker
language: java
branches:
  only:
  - master
jdk:
- oraclejdk8
script:
- mvn verify
- mvn dockerfile:push
before_install:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
install: echo "We believe in Maven."
cache:
  directories:
  - "$HOME/.m2"